#!/usr/bin/env bash

# pm2 post-deploy

if [ "$(git symbolic-ref HEAD 2>/dev/null)" == "refs/heads/master" ] ; then
  echo "Checking if *.hbs files changed."
  # precompile assets if any have been updated
  if git diff-index --name-only HEAD^ | egrep '*.hbs$' >/dev/null ; then
    pm2 reload ghost
  else
    echo "*.hbs hasn't changed."
  fi
fi
