#!/bin/bash

#.git/hooks/pre-push

if [ "$(git symbolic-ref HEAD 2>/dev/null)" == "refs/heads/master" ] ; then
  echo "Checking if assets/less changed."
  # precompile assets if any have been updated
  if git diff-index --name-only HEAD | egrep '^assets/less' >/dev/null ; then
    echo "Precompiling less"
    gulp less --env production
    git add -A assets/
    echo "Added production assets"
  else
    echo "Assets hasn't changed."
  fi
fi
